// Generates vendor/i18n.js for the classic game from the shared site catalog,
// so translations live in exactly one place (remaster/src/i18n/catalog.ts).
import { mkdir } from "node:fs/promises";
import { join, resolve } from "node:path";
import { CATALOG, LANGS, RTL_LANGS } from "../../remaster/src/i18n/catalog";

const legacyDir = resolve(import.meta.dir, "..");

const js = `// Generated by scripts/gen-i18n.ts — do not edit by hand.
window.BUBBLES_I18N = ${JSON.stringify({ langs: LANGS, rtl: RTL_LANGS, catalog: CATALOG })};
window.BI18N = (function () {
	var data = window.BUBBLES_I18N;
	var lang = (function () {
		try {
			var saved = localStorage.getItem("bubbles.lang");
			if (saved && data.catalog[saved]) return saved;
		} catch (e) {}
		var base = ((navigator.language || "en").toLowerCase()).slice(0, 2);
		return data.catalog[base] ? base : "en";
	})();
	function t(key) {
		var c = data.catalog[lang] || data.catalog.en;
		return c[key] || data.catalog.en[key] || key;
	}
	function fmt(key, vars) {
		return t(key).replace(/\\{(\\w+)\\}/g, function (m, k) {
			return vars && k in vars ? String(vars[k]) : m;
		});
	}
	return { lang: lang, langs: data.langs, t: t, fmt: fmt };
})();
`;

await mkdir(join(legacyDir, "vendor"), { recursive: true });
await Bun.write(join(legacyDir, "vendor", "i18n.js"), js);
console.log("vendor/i18n.js");
